config/routes.rb
Rails.application.routes.draw do
  resources :comensales 
  resources :menus

  devise_for :users

   root 'comensales#index'
  

end

app/models/comensale.rb
class Comensale < ActiveRecord::Base

	
	
	validates :mail, :presence => {:message => "Debe ingresar su email"}
	validates :tipo_comensal, :presence => {:message => "Debe ingresar el Tipo de Comensal"}
	
	validates :cantidad, :presence => {:message => "Debe ingresar la cantidad de Comensales"}


	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |comensale|
				csv << Comensale.attributes.values_at(*column_mail)
			end
		end
	end

end

app/controllers/comensales_controller.rb
class ComensalesController < ApplicationController
  before_action :set_comensale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /comensales
  # GET /comensales.json
  def index
  	
 
	# strftime - formatear tiempo (stringfy time)
	# %d - día (day)
	# %m - mes (month)
	# %Y - año (year)
	# %H - hora en formato 24 horas (hour)
	# %M - minuto
	# %S - segundo (second)
  	
  	fecha_hoy = Date.today()
	dia  = fecha_hoy.strftime("%d")
	mes  = fecha_hoy.strftime("%m")
	anio = fecha_hoy.strftime("%Y")
  

  	@comensales_date = fecha_hoy

	tipo_empleado = "Empleado"
	tipo_director = "Director"
	tipo_gerente  = "Gerente"
	tipo_invitado = "Invitado"

	limite_inicial = Time.gm(anio,mes,dia,07,00,00)
	limite_normal  = Time.gm(anio,mes,dia,11,00,00)
	limite_tarde   = Time.gm(anio,mes,dia,13,00,00)

    
    @comensales = Comensale.where("fecha_notificacion >= ? and fecha_notificacion <= ?", limite_inicial, limite_tarde)
    #@comensales = Comensale.where(fecha_notificacion: DateTime.now().hour)
    #@fecha = (DateTime.now).hour
    #@fecha = @comensales.length

    @comensales_count_total  = Comensale.where("fecha_notificacion >= ? and fecha_notificacion <= ?", limite_inicial, limite_tarde ).sum(:cantidad)
    @comensales_count_normal = Comensale.where("fecha_notificacion >= ? and fecha_notificacion <= ?", limite_inicial, limite_normal).sum(:cantidad)
    @comensales_count_tarde  = Comensale.where("fecha_notificacion > ? and fecha_notificacion <= ?", limite_normal,  limite_tarde ).sum(:cantidad)

    @comensales_count_empleado = Comensale.where("fecha_notificacion >= ? and fecha_notificacion <= ? and tipo_comensal = ?", limite_inicial, limite_tarde, tipo_empleado).sum(:cantidad)
    @comensales_count_director = Comensale.where("fecha_notificacion >= ? and fecha_notificacion <= ? and tipo_comensal = ?", limite_inicial, limite_tarde, tipo_director).sum(:cantidad)
    @comensales_count_gerente  = Comensale.where("fecha_notificacion >= ? and fecha_notificacion <= ? and tipo_comensal = ?", limite_inicial, limite_tarde, tipo_gerente).sum(:cantidad)
    @comensales_count_invitado_normal = Comensale.where("fecha_notificacion >= ? and fecha_notificacion <= ? ", limite_inicial, limite_normal).sum(:invitados)
    @comensales_count_invitado_tardes = Comensale.where("fecha_notificacion >= ? and fecha_notificacion <= ? ", limite_normal, limite_tarde).sum(:invitados)
    @user = current_user


    respond_to do |format|
      format.html
      format.xls
    end


  end


  # GET /comensales/1
  # GET /comensales/1.json
  def show
  end

  # GET /comensales/new
  def new
    @comensale = Comensale.new
  end

  # GET /comensales/1/edit
  def edit
  end

  # POST /comensales
  # POST /comensales.json
  def create
    @comensale = Comensale.new(comensale_params)
    @comensale.save()

    respond_to do |format|
      if @comensale.save
        format.html { redirect_to @comensale, notice: 'Se ha agregado una nueva entrada' }
        format.json { render :show, status: :created, location: @comensale }
      else
        format.html { render :new }
        format.json { render json: @comensale.errors, status: :unprocessable_entity, notice: 'No se pudo' }
      end
    end
  end

  # PATCH/PUT /comensales/1
  # PATCH/PUT /comensales/1.json
  def update
    respond_to do |format|
      if @comensale.update(comensale_params)
        format.html { redirect_to @comensale, notice: 'Comensale was successfully updated.' }
        format.json { render :show, status: :ok, location: @comensale }
      else
        format.html { render :edit }
        format.json { render json: @comensale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comensales/1
  # DELETE /comensales/1.json
  def destroy
    @comensale.destroy
    respond_to do |format|
      format.html { redirect_to comensales_url, notice: 'Comensale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comensale
      @comensale = Comensale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comensale_params
      params.require(:comensale).permit(:id_legajo,:mail, :tipo_comensal, :proyecto, :fecha_notificacion, :cantidad, :invitados)
    end
end

app/helpers/comensales_helper.rb
module ComensalesHelper
end

app/views/comensales/_form.html.erb
<!DOCTYPE html>
<html>
  <script>
  function valida(e){
      tecla = (document.all) ? e.keyCode : e.which;
      //Tecla de retroceso para borrar, siempre la permite
      if (tecla==8){
          return true;
      }
          
      // Patron de entrada, en este caso solo acepta numeros
      patron =/[0-9]/;
      tecla_final = String.fromCharCode(tecla);
      return patron.test(tecla_final);
  }
  </script>
  <script type="text/javascript">
      function showContent() {
          element = document.getElementById("content");
          check = document.getElementById("check");
          if (check.checked) {
              element.style.display='block';
          }
          else {
              element.style.display='none';
          }
      }
  </script>

  <% 
    fecha_hoy = Time.new
    
    horaTarde = 13
    minutoTarde = 00
    hora = fecha_hoy.strftime("%H")
    minuto = fecha_hoy.strftime("%M")
    hora = hora.to_i
    minuto = minuto.to_i
    esTarde = false
    if hora > horaTarde
      esTarde = true
    end
    
    if minuto > minutoTarde && hora == horaTarde
      esTarde = true
    end
  %>
<head>
  <title>Com&eacute;s hoy? </title>
</head>
<body>

<div class="container" style="text-align: center;">
  <% if !esTarde %>
    <h1 style="text-align: center">Hoy vas a comer?</h1>

    <div class="container" style="width: 50%">
        <%= form_for(@comensale) do |f| %>
          <% if @comensale.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@comensale.errors.count, "error") %> prohibited this comensale from being saved:</h2>

              <ul>
              <% @comensale.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

            <form role="form" action="/comensales/create" class="nifty_form" method="post" >
              <div class="form-group">
                  <% if(user_signed_in?) %>
                    <input type="text" class="form-control hidden" id="legajo_1" onkeypress="return valida(event)"
                        value=<%= current_user.legacy %> placeholder="Introduce tu legajo" name=comensale[id_legajo]>
                    
                  <% else %>
                    <input type="text" class="form-control" id="legajo_1" onkeypress="return valida(event)"
                                 placeholder="Introduce tu legajo" name=comensale[id_legajo]>
                <% end %>   
              </div>
              <div class="form-group">
                <label for="mail_1"><%= f.label :mail %></label>
                <% if(user_signed_in?) %>
                  <input type="email" class="form-control" id="mail_1"
                      value=<%= current_user.email %> placeholder="Introduce tu email" name=comensale[mail]>
                <% else %>
                  <input type="email" class="form-control" id="mail_1"
                       placeholder="Introduce tu email" name=comensale[mail]>
                <% end %>
              </div>
              <div class="form-group">
                <label for="text">Agregar invitado</label>
                <input type="checkbox" name="check" id="check" value="0" onchange="javascript:showContent()" />
              </div>


              <div class="form-group" id='content' style='display:none;'>
                <label for="number"><%= f.label :invitados %></label>
                <select class="selectpicker" name = comensale[invitados]>
                  <option>0</option>
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                  <option>5</option>
                  <option>6</option>
                  <option>7</option>
                </select>
              </div>      

              <div class="actions">
                <%= f.submit "Hoy voy a comer" %>
              </div>    
              <div class="form-group" style="visibility:hidden">
                <label for="text"><%= f.label :fecha_notificacion %></label>
                <input id="fecha_1" name="comensale[fecha_notificacion]" type="date" value="<%=Time.now.strftime("%d-%m-%Y %R")%>"  />
              </div>
              <div class="form-group" style="visibility:hidden">
                <label for="number"><%= f.label :cantidad %></label>
                <input id="cantidad1" name="comensale[cantidad]" type="number" value="1"  />
              </div>
              <div class="form-group" style="visibility:hidden">
                <label for="text"><%= f.label :tipo_comensal %></label>
                <input id="comensal1" name="comensale[tipo_comensal]" type="text" value="Empleado"  />
              </div>
            </form>
      <% end %>
    </div>
  <% else %>
      <h2>Ya estamos comiendo, pas&aacute; por el comedor</h2>
      <p>Por favor acordate de avisar antes de las 11:00 A.M.</p>                  
        <%=image_tag("tarde.jpg", class: "img-rounded", width:"601", height:"300")%>
      <p>M&aacute;s suerte la pr&oacute;xima</p> 
  <% end %>

</div>
    <%= link_to "Volver", comensales_path, {style: 'color: white;', :class=>'btn btn-warning'}  %>
</body>
</html>

app/views/comensales/edit.html.erb
<h1>Editing Comensale</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @comensale %> |
<%= link_to 'Volver', comensales_path %>

app/views/comensales/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<p id="notice"><%= notice %></p>

<h1 style="text-align: center">Lista de Comensales</h1>



<div class="container">
  <h2>¿Quién come hoy?</h2>
 
  <SECTION class="col-sm-12" style="margin-bottom: 25px">
    <h1 style="text-align: center">Comensales</h1><br><br>
    
    <div class="col-sm-4" style="background: #006400; color: white; padding-bottom: 50px; padding-top: 50px">
      <h2 style="text-align: center">Total (<%= @comensales_count_total %>)</h2>  
    </div>

    <div class="col-sm-4" style="background: #003DF5; color: white; padding-bottom: 50px; padding-top: 50px">
      <h2 style="text-align: center">A horario (<%= @comensales_count_normal+@comensales_count_invitado_normal%>)</h2>
    </div>
    
    <div class="col-sm-4" style="background: #FF0000; color: white; padding-bottom: 50px; padding-top: 50px " >
      <h2 style="text-align: center">Tarde (<%= @comensales_count_tarde+@comensales_count_invitado_tardes %>)</h2>

    </div>

  </SECTION>
  <h2>
  <%= link_to "Agregar comensales", new_comensale_path, {style: 'color: white', :class => "btn btn-primary"}  %>
  
  <%= link_to "Ver menús", menus_path, {style: 'color: white', :class => "btn btn-success"}  %>
  </h2>


  <table class="table">
    <thead>
      <tr>
        <th>Mail</th>
        <th>Tipo comensal</th>
        <th>Fecha notificacion</th>
        <th>Cantidad</th>
        <th>Invitados</th>
        <!--
        <th colspan="3"></th>
        -->
      </tr>
    </thead>
    <tbody>
      <% @comensales.each do |comensale| %> 
      <tr>
        <td><%= comensale.mail %></td>
        <td><%= comensale.tipo_comensal %></td>
        <td><%= comensale.fecha_notificacion.strftime('%d/%m/%Y %H:%M:%S')%></td>
        <td><%= comensale.cantidad %></td>
        <td><%= comensale.invitados %></td>
        <!--
        <td><%= link_to 'Show', comensale %></td>
        <td><%= link_to 'Editar', edit_comensale_path(comensale) %></td>
        -->
        <td><%= link_to 'Eliminar', comensale, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        
      </tr>
      <% end %>
    </tbody>
  </table>

  <% if @user.admin %> 
      <%= link_to "Descargar en Excel", comensales_path(format: "xls"), {style: 'color: white', :class => "btn btn-primary"}%>
  <% end %>

</div>

app/views/comensales/index.xls.erb
<table border="1" align="center">
	<tr>
		<th>Fecha</th>
		<th>Empleados</th>
		<th>Invitados</th>
		<th>Total</th>
	</tr>

        <% Comensale.select(:fecha_notificacion, "SUM(invitados) as invitados", "SUM(cantidad) as cantidad").group('fecha_notificacion').each do |comensale| %>
          <tr>
            <td><%= comensale.fecha_notificacion.strftime('%d/%m/%Y') %></td>
            <td><%= comensale.cantidad %></td>
            <td><%= comensale.invitados %></td>
            <td><%= comensale.cantidad + comensale.invitados %></td>
           </tr>
        <% end %>
        <% Comensale.select("SUM(invitados) as invitados", "SUM(cantidad) as cantidad").each do |comensale| %>
          <tr>
            <td></td>
            <td><%= comensale.cantidad %></td>
            <td><%= comensale.invitados %></td>
            <td><%= comensale.cantidad + comensale.invitados %></td>
          </tr>
        <% end %>

</table>

app/views/comensales/new.html.erb
<%= render 'form' %>

app/views/comensales/show.html.erb
<html>
  <p id="notice"><%= notice %></p>
  <script>
  function valida(e){
      tecla = (document.all) ? e.keyCode : e.which;
      //Tecla de retroceso para borrar, siempre la permite
      if (tecla==8){
          return true;
      }
          
      // Patron de entrada, en este caso solo acepta numeros
      patron =/[0-9]/;
      tecla_final = String.fromCharCode(tecla);
      return patron.test(tecla_final);
  }
  </script>
  <script type="text/javascript">
      function showContent() {
          element = document.getElementById("content");
          check = document.getElementById("check");
          if (check.checked) {
              element.style.display='block';
          }
          else {
              element.style.display='none';
          }
          showBotonSub();
      }
      function showBotonSub() {
          element = document.getElementById("botonSub");
          check = document.getElementById("check");
          if (check.checked) {
              element.style.display='block';
          }
          else {
              element.style.display='none';
          }
      }
  </script>

  <head>
    <title>Gracias por informar!</title>
  </head>
  <body>
  <table class="table">
    <thead>
      <tr>
        <th>Mail</th>
        <th>Tipo comensal</th>
        <th>Fecha notificacion</th>
        <th>Invitados</th>
    </thead>
    <tbody>
      <tr>
        <td><%= @comensale.mail %></td>
        <td><%= @comensale.tipo_comensal %></td>
        <td><%= @comensale.fecha_notificacion.strftime('%d/%m/%Y %H:%M:%S')%></td>
        <td><%= @comensale.invitados %></td>
      </tr>
    </tbody>
  </table>

<!--
  <div>
    <%= form_for(@comensale) do |invitado| %>
    <div class="form-group">
      <label for="text">Agregar invitado</label>
      <input type="checkbox" name="check" id="check" value="1" onchange="javascript:showContent()" />
    </div>
    <form method="POST" name="envio" action="/comensales/create" id="form_invitados">
      <input type = "hidden" name = "invitado_tipo"   value = "Invitado"/>
      <input type = "hidden" name = "invitado_legajo" value =<%= current_user.legacy %>/>
      <input type = "hidden" name = "invitado_mail"   value =<%= current_user.email %>/>
      <input type = "hidden" name = "invitado_fecha"  value = "<%=Time.now.strftime("%Y-%m-%d %R")%>"/>

      <div class="form-group" id='content' style='display:none;'>
        <label for="number"><%= invitado.label :cantidad %></label>
        <select class="selectpicker" name = comensale[cantidad]>
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
          <option>6</option>
          <option>7</option>
        </select>
      </div>
      <div class="form-group" style="visibility:hidden">
        <label for="text"><%= invitado.label :fecha_notificacion %></label>
        <input id="fecha_2" name="comensale[fecha_notificacion]" type="date" value="<%=Time.now.strftime("%d-%m-%Y %R")%>"  />
      </div>
      <div class="form-group" style="visibility:hidden">
        <label for="text"><%= invitado.label :tipo_comensal %></label>
        <input id="comensal2" name="comensale[tipo_comensal]" type="text" value="Invitado"  />
      </div>
      
      <div class="actions" id='botonSub' style='display: none'>
        <%= invitado.submit "Hoy voy a comer" %>
      </div>
      
    </form>

  </div>
  <% end %>
-->
<%= link_to 'Editar', edit_comensale_path(@comensale) %> |
<%= link_to 'Volver', comensales_path %>


</body>
</html>