config/routes.rb
Rails.application.routes.draw do
  resources :comensales 
  resources :menus

  devise_for :users

   root 'comensales#index'
  

end

app/models/menu.rb
class Menu < ActiveRecord::Base

	
	#validates that fields are not empty
	validates :dish, :presence => {:message => ": Debe ingresar el nombre del plato"}
	validates :day, :presence => {:message => ": Debe ingresar los días que estara disponible"}

	

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  #before_action :authenticate_user!
  before_action :set_menu, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /menus
  # GET /menus.json
  def index
   
    @menus = Menu.all

    # Hay que ver como hacer para obtener el dia de hoy
    @menus_del_dia = Menu.where(day: Date.today())
    @user = current_user;

  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  #   GET /menus/1/edit
  def edit

  end


  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)
    #@menu.day = Date.today() 
      
    if @menu.save();
     redirect_to @menu, notice: 'El menu se creo exitosamente.' 
    else
      redirect_to new_menu_path, notice: "Hubo un problema, inténtelo de nuevo"      
    end
    
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'El menu se actualizo exitosamente.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'El menu se elimino exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:dish, :day)
    end
end

app/helpers/menus_helper.rb
module MenusHelper

	def checked(area)

		@menu.day.nil? ? false : @menu.day.match(area)
		
	end

end

app/views/menus/2index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center;">Lista de Menus</h1>

<table border="1" width="30%" cellpadding="0" cellspacing="0" align="center">
  <thead>
    <tr>
      <th>Platos</th>
      <th>Días disponibles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.dish %></td>
        <td><%= menu.day %></td>
        <td><%= link_to 'Editar', edit_menu_path(menu) %></td>
        <td><%= link_to 'Eliminar', menu, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<!-- /////////////////////////////CARRUSEL ////////////////////////////// !-->
<div class="container" style="text-align: center;">
  <div class="row">
    <div class="col-sm-12">
      <div id="my-slider" class="carousel slide" data-ride="carousel">
        
        <!-- botones  -->
        <!--
        <ol class="carousel-indicators">
          <li data-target="#my-slider" data-slide-to="0" class="active"></li>
          <li data-target="#my-slider" data-slide-to="1"></li>
          <li data-target="#my-slider" data-slide-to="2"></li>
        </ol>
        -->
          
        <div class="carousel-inner" role="listbox">
   
          <!-- cada parte y la active es la primera -->
          <div class="item active">
            <h1>Menu de Hoy</h1>
          </div>

          <!-- Si puedo meter esto en comensales deberia andar -->
          <% @menus_del_dia.each do |menu| %>
            <div class="item">
            
              <h1><%= menu.dish %></h1>
            </div>
          <%end%>

        </div>

        <!-- next and prev  -->
        <a class="carousel-control left" href="#my-slider" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control right" href="#my-slider" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>

      </div>
    </div>
  </div>
</div>

<!-- /////////////////////////FIN CARRUSEL ///////////////////////////// !-->
<br>

<%= link_to 'Agregar nuevo Menu', new_menu_path %><br>
<%= link_to 'Volver al registro', comensales_path %>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Plato %><br>
    <%= f.text_field :dish %>
  </div>
  <div class="field">
    
    <%= f.label :Días_Disponible %><br>

    
    <%= check_box_tag 'menu[day][]', 'Lunes', checked('Lunes'), id: 'day_lunes' %>
    <%= label_tag 'day_lunes', 'Lunes' %><br>

    
    <%= check_box_tag 'menu[day][]', 'Martes', checked('Martes'), id: 'day_martes' %>
    <%= label_tag 'day_martes', 'Martes' %><br>

    
    <%= check_box_tag 'menu[day][]', 'Miercoles', checked('Miercoles'), id: 'day_miercoles' %>
    <%= label_tag 'day_miercoles', 'Miercoles' %><br>

    
    <%= check_box_tag 'menu[day][]', 'Jueves', checked('Jueves'), id: 'day_jueves' %>
    <%= label_tag 'day_jueves', 'Jueves' %><br>

    
    <%= check_box_tag 'menu[day][]', 'Viernes', checked('Viernes'), id: 'day_viernes' %>
    <%= label_tag 'day_viernes', 'Viernes' %>


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editar Menu</h1>

<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Plato %><br>
    <%= f.text_field :dish %>
  </div>

  <div class="field">
    <%= f.label :Día %><br>
    <%= f.date_select :day %>
  </div>
    
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

<%= link_to 'Mostrar', @menu %> |
<%= link_to 'Volver', menus_path %>

app/views/menus/index.html.erb
<h1 style="text-align: center;">Menú de hoy</h1>
<table border="1" width="60%" cellpadding="0" cellspacing="0" align="center" style="margin-bottom: 60px">
  <thead>
    <tr>
      <th>Platos</th>
      <th>Días disponibles</th>
      <% if @user.admin %>
          <th colspan="3"></th>
      <% end %>    
    </tr>
  </thead>

  <tbody>
    <% @menus_del_dia.each do |menu| %>
      <tr>
        <td><%= menu.dish %></td>
        <td><%= menu.day.strftime('%d/%m/%Y') %></td>
        <% if @user.admin %>
        <td><%= link_to 'Editar', edit_menu_path(menu) %></td>
        <td><%= link_to 'Eliminar', menu, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<% if @user.admin %>
<div  style="margin-bottom: 60px" >
<%= link_to 'Crear nuevo menú', new_menu_path, :style => "color: white;", :class=>"btn btn-primary col-sm-2 col-sm-offset-5" %>
</div>
<br>

<% end %>

<h1 style="text-align: center;" class="col-sm-12">Menúes históricos</h1>
<table border="1" width="60%" cellpadding="0" cellspacing="0" align="center" >
  <thead>
    <tr>
      <th>Platos</th>
      <th>Días disponibles</th>
      <% if @user.admin %>
      <th colspan="3"></th>
      <% end %> 
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.dish %></td>
        <td><%= menu.day.strftime('%d/%m/%Y') %></td>
        <% if @user.admin %>
        <td><%= link_to 'Editar', edit_menu_path(menu) %></td>
        <td><%= link_to 'Eliminar', menu, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div style="text-align: center;">
  <%= link_to "Volver a la página principal", comensales_path, {style: 'color: white;', :class=>'btn btn-warning'}  %>
</div>

app/views/menus/new.html.erb
<h1 style="text-align: center">Nuevo Menu</h1>

<div class="col-sm-4 col-sm-offset-4" style="text-align: center">
  <%= form_for(@menu) do |f| %>

    <% if @menu.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>
        <ul>
        <% @menu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :Plato %><br>
      <%= f.text_field :dish, :style => "width: 100%" %>
    </div>

    <div class="field">
      <%= f.label :Día %><br>
      <%= f.date_select :day, {:use_month_names => ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"] , :style => "width: 100%"} %>
    </div>
    
    <div class="">  
      <div class="actions" >
        <%= f.submit "Crear menú", style: "width: 60%", class: "btn btn-primary" %>
      </div>
      
      <%= link_to 'Volver a los menús', menus_path, :class => "center-block btn btn-success", :style => "width: 40%; color: white" %>
    </div>
    
  <% end %>
</div>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plato:</strong>
  <%= @menu.dish %>
</p>

<p>
  <strong>Días disponible:</strong>
  <%= @menu.day %>
</p>

<%= link_to 'Editar', edit_menu_path(@menu) %> |
<%= link_to 'Volver', menus_path %>